{% set version = "1.15" %}

package:
  name: pypandoc
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pypandoc/pypandoc-{{ version }}.tar.gz
  sha256: ea25beebe712ae41d63f7410c08741a3cab0e420f6703f95bc9b3a749192ce13

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip >=8.1.0
    - pandoc
    - poetry-core
    - setuptools
    - wheel >=0.25.0
  run:
    - python
    - pandoc

test:
  imports:
    - pypandoc
  commands:
    - python -c "import pypandoc; print(pypandoc.get_pandoc_version())"

about:
  home: https://github.com/NicklasTegner/pypandoc
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Thin wrapper for "pandoc"
  dev_url: https://github.com/NicklasTegner/pypandoc
  doc_url: https://pypi.org/project/pypandoc/

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
