{% set version = "1.2.0" %}
package:
  name: pypandoc
  version: {{ version }}

source:
  fn: pypandoc-{{ version }}.zip
  url: https://github.com/bebraw/pypandoc/archive/v{{ version }}.zip
  sha1: 4cd42a1e987223bbee639ac28d05ba516bad7071


build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pandoc
  run:
    - python
    - pandoc

test:
  imports:
    - pypandoc
  commands:
    - python -c "import pypandoc; print(pypandoc.get_pandoc_version())"

about:
  home: https://github.com/bebraw/pypandoc
  license: MIT
  summary: 'Thin wrapper for "pandoc"'

extra:
  recipe-maintainers:
    - janschulz
