{% set version = "1.7.2" %}

package:
  name: pypandoc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pypandoc/pypandoc-{{ version }}.tar.gz
  sha256: 035c04648c1f95f817252bcc85abda11804d7d5ea577f84b51fa2ced6d9768f2

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip >=8.1.0
    - wheel >=0.25.0
    - setuptools
    - pandoc
  run:
    - python
    - pandoc

test:
  imports:
    - pypandoc
  commands:
    - python -c "import pypandoc; print(pypandoc.get_pandoc_version())"

about:
  home: https://github.com/NicklasTegner/pypandoc
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Thin wrapper for "pandoc"'
  dev_url: https://github.com/NicklasTegner/pypandoc
  doc_url: https://pypi.org/project/pypandoc/

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
