travis:
  secure:
    BINSTAR_TOKEN: f9W3Dk9emQ5y53EcEl46L2+pyBCBoBJilAppid3y8Rw+aN8W+xWd6XxqFwzrVtIUsC7MPiJCjRqxMDL9zdiMJdw2AHBOmzJQwyU9LuONABTwIyQSL6emPQSzoDRpaYVxRlO/BRMArVCZ6vm4WJOzEVyT/tFyJ1HVEJQ45U/O+QOgxqLsvjRLbLsWH5XCRkfz2hs6vY/GpXR4XnDg+nAbSkXrpTOp8XBB/9O7x4QII1TupKKnTXkb97KMR9MttyziwaMcnT87ZbRafkkbXu6iXzP80O3NR3ks95rCUWufYtGdzECasID25g5rxqOW57BeB72dMJBVPDBC+l1XJ6d2NmSIKhdBcYOp2irZGcpnVr/LzZTWdHGO7RRv9l5YHzxnGArY1C1HnX7+P3c9wFgxeF7fYyYHZgQN7sPTnMxIp9Wu/DTHH+OZ+7iHiGHlNP4q2kS+zVbeHBHONOHRgYqc1G3DjPbrGlE10zi+BnG7QPr2Ew0vdMTJhU4ZBgWu7RshiOyKzCgNuiK920jRN4KsfoBbkNQ8fAbwOvAK1eU/5xJNYK9lZolo87g5lMDmsBN6sahNrfM541PyhX6RDMz1exHxYNMK/Y/5haV5rdE332S782CddHrgkF2P9As5oe3nacm0krqrM9xw2/oI232OhqU7JzdNntGtgn6DshJSx7w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
