travis:
  secure:
    BINSTAR_TOKEN: tfgsFy3M3KA2WFR7BS3Kwh0aCO5DnSsOk76Kk4K91dCztNqfbVYzaCE28i735HmKjkf0LpxkRB1rdHwNbQnn/H+ZJLXp4BelRXisB6jWWV9CQ4FI81i8QCoey6GzNtmjDK3Ls/3aQxlPJLdUVe8X2SiXFHSOkhS63HiH2jk8OaAo9SiAXVlWfgjDSNQxAJj+tbBX2QD5aLgMNSW4NcW/mNVG9xjVDqvcchp6m27kUosv4FQyZMYZS82y3FN77CVWewv5xmI5j07mwKRwafn4uuF6uBAqWF191C3dLJmKoV8y8vSQ+04nK5yaRev2zvoYalkyS2PW6TCZpAR9MKYUdlA7uZ1CnIMD/GXMvsG/MNZk2xHL5cryHaAhsaoYFrRl7NQvk8f+LFIW9S9dDTTozsUjfJepheFUS874/TwaBgFKLnyVs4uI1OkcRbEwypqAHolDNzVi/NHpJXrjNA+yr/rm+MVkPsjqIQxmmtpl37hoCGplydRnuC1swib+F05TSV+lQfjwavEUi3OpHuEPtT9fGRiRYiIYPdAMYWQpfl4QuJQ+AMkDFvynjVY3OfMKw5Krpe5guxE9sh9V/HyJeLirLgGkvvGsnCH52y9z+ewJo4VlrzjpEWVMHypkXRGg5MCNQUNDsVIrR68Uc76AVxl8xQvsO+a0sksMbVC99E4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
